[package]
name = "orm-module"
version = "0.1.0"
edition = "2024"

[dependencies]
diesel = { workspace = true , features = ["postgres"]}
dotenvy = { workspace = true }
diesel-derive-enum = { workspace = true }
# diesel_filter = { workspace = true }
chrono = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
utils = { workspace = true }