[package]
name = "extending"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { workspace = true }
diesel = { workspace = true }
#diesel_filter = { workspace = true }
diesel_pagination = { workspace = true }
pgtrgm = { workspace = true }
itertools = "0.14.0"
orm-module = { workspace = true }


[[bin]]
name = "sql-function"
path = "src/sql_function.rs"

[[bin]]
name = "pagination"
path = "src/pagination.rs"

[[bin]]
name = "trigrams"
path = "src/trigrams.rs"