[package]
name = "all-about-select"
version = "0.1.0"
edition = "2024"

[dependencies]
diesel = { workspace = true }
orm-module = { workspace = true }
rand = "0.9.2"

[[bin]]
name = "without-from"
path = "src/without_from.rs"

[[bin]]
name = "fill-users"
path = "src/fill_users.rs"

[[bin]]
name = "run-query-dsl"
path = "src/run_query_dsl.rs"

[[bin]]
name = "via-query-dsl"
path = "src/via_query_dsl.rs"

[[bin]]
name = "has-query"
path = "src/has_query.rs"

[[bin]]
name = "nested-tuples"
path = "src/nested_tuples.rs"