DROP TABLE IF EXISTS enrollments;
DROP TABLE IF EXISTS courses;
DROP FUNCTION IF EXISTS enroll_student_in_course(VARCHAR, VARCHAR, VARCHAR);
DROP FUNCTION IF EXISTS upsert_user(VARCHAR, VARCHAR);
DROP FUNCTION IF EXISTS upsert_course(VARCHAR);
DROP FUNCTION IF EXISTS enroll_student(VARCHAR, VARCHAR);