[package]
name = "diesel-tutorial"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenvy = { workspace = true }

[workspace.dependencies]
diesel = { version = "2.3.4", features = ["postgres"] }
dotenvy = "0.15.7"
orm-module = { path = "./orm-module" }
utils= {path = "./utils"}

[workspace]
members = ["all-about-select","check-connection", "delete-car", "get-cars", "insert-cars", "one-off-update", "orm-module", "struct-encap-update", "update-car", "utils"]
