[package]
name = "diesel-tutorial"
version = "0.1.0"
edition = "2024"

[dependencies]
diesel_migrations = "2.3.1"
dotenvy = { workspace = true }
orm-module = { workspace = true }


[workspace.dependencies]
clap = { version = "4.5.56", features = ["derive"] }
diesel = { version = "2.3.6", features = ["postgres", "chrono", "serde_json"] }
# diesel_filter = { version = "2.0.0" }
diesel_pagination = { version = "2.0.0" }
dotenvy = "0.15.7"
orm-module = { path = "./orm-module" }
utils = { path = "./utils" }
diesel-derive-enum = { version = "3.0.0-beta.1", features = ["postgres"] }
chrono = { version = "0.4.43", features = ["serde"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = { version = "1.0.149" }
itertools = "0.14.0"
pgtrgm = { version = "0.4.0", features = ["diesel"] }
diesel_full_text_search = "2.3.0"
diesel_json = "0.3.0"
[workspace]
members = ["all-about-select", "first-steps", "graphs", "orm-module", "extending", "relations", "stored-procedures", "struct-encap-update", "utils", "nlp", "json"]
