[package]
name = "graphs"
version = "0.1.0"
edition = "2024"

[dependencies]
orm-module = { workspace = true }
diesel = { workspace = true }
utils = { workspace = true }
serde_json = { workspace = true }
diesel-cte-ext = { version = "0.1", default-features = false, features = [
    "postgres",
] }
[[bin]]
name = "fill"
path = "src/fill.rs"

[[bin]]
name = "with-recursive"
path = "src/with_recursive.rs"

[[bin]]
name = "find-prs"
path = "src/find_prs.rs"